#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected="$(~/.config/bin/ssh-menu -s)"
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name="ssh_$selected"

if [[ -z $TMUX ]] && ! tmux list-sessions 2>/dev/null; then
    tmux new-session -s "$selected_name" ssh "$selected"
    exit 0
fi

if ! tmux has-session -t="$selected_name" 2>/dev/null; then
    tmux new-session -ds "$selected_name" ssh "$selected"
fi

tmux switch-client -t "$selected_name"
