# daemon
exec mako
exec swayidle -w
exec wlsunset -l 46.1 -L 14.5
exec pkill -x wob; rm -f $wobs && mkfifo $wobs && tail -f $wobs | wob
exec wl-paste --watch cliphist store
exec ~/.config/sway/scripts/power-aware-effects.sh
exec protonmail-bridge -n

# traditional "start when os starts" programs
exec ghostty --title=fastfetch --window-width=105 --window-height=27 -e bash -c 'nix run nixpkgs#fastfetch; read -rsn1' && ghostty
exec $browser
exec thunderbird
exec cider-2
exec bolt-launcher
exec discord
exec slack
exec Telegram
exec rocketchat-desktop
exec 1password --silent
