# bottom-aligned and adjacent to eDP-1 at scale 1
# NOTE:(@janezicmatej) scripts/output-scale.sh recomputes both positions on scale change
output DP-7 resolution 2560x1440 position 2560 160
output eDP-1 resolution 2560x1600@165Hz position 0 0 scale 1 adaptive_sync on
