#!/usr/bin/env bash

source "$XDG_CONFIG_HOME/zsh/scripts.zsh"

if [[ $# -eq 1 ]]; then
    selected=$1
else
    read -p "ssh url: " selected
fi

if [[ -z $selected ]]; then
    exit 0
fi

ggman clone "$selected"
ggcompile
